name: 'Labeler'
description: 'Add labels to new pull requests based on the files that are changed'
author: 'GitHub'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  shared-configurations-token:
    description: 'The Github token used to access shared configs'
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
    required: false
  shared-configurations:
    description: "Github locations of shared configuration files"
    default: "[]"
    required: false
  sync-labels:
    description: 'Whether or not to remove labels when matching files are reverted'
    default: false
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
